-- AddColumn new e-CF type sequence fields to ecf_config
ALTER TABLE "ecf_config" ADD COLUMN IF NOT EXISTS "ncfGastosMenores" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "ecf_config" ADD COLUMN IF NOT EXISTS "ncfGubernamental" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "ecf_config" ADD COLUMN IF NOT EXISTS "ncfExportaciones" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "ecf_config" ADD COLUMN IF NOT EXISTS "ncfPagosExterior" INTEGER NOT NULL DEFAULT 1;

-- AlterEnum: Add new values to InvoiceType enum
ALTER TYPE "InvoiceType" ADD VALUE IF NOT EXISTS 'COMPRAS';
ALTER TYPE "InvoiceType" ADD VALUE IF NOT EXISTS 'GASTOS_MENORES';
ALTER TYPE "InvoiceType" ADD VALUE IF NOT EXISTS 'GUBERNAMENTAL';
ALTER TYPE "InvoiceType" ADD VALUE IF NOT EXISTS 'EXPORTACIONES';
ALTER TYPE "InvoiceType" ADD VALUE IF NOT EXISTS 'PAGOS_EXTERIOR';
